# -*- coding: utf-8 -*-
"""BAB 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F9mgeyB7mNbfafpsVN1Tc6cCzJ2SZO2U

Bab 1: Pengantar Machine Learning

Implementasi kode
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

# Load dataset Iris
iris = load_iris()
print("Kunci dataset:", iris.keys())

# Split dataset jadi data training & testing
X_train, X_test, y_train, y_test = train_test_split(
    iris['data'], iris['target'], random_state=0
)

# Bikin model k-Nearest Neighbors (k-NN)
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)

# Prediksi hasil dari data testing
predictions = knn.predict(X_test)
accuracy = knn.score(X_test, y_test)
print("Prediksi hasil data testing:", predictions)
print("Akurasi data testing:", accuracy)

"""## 3. Penjelasan Teoritis
- **Supervised Learning**: Prediksi label berdasarkan pasangan input-output yang udah diketahui.
- **Dataset Iris**: Dataset klasik dengan fitur kayak panjang-lebar kelopak (sepal) dan mahkota (petal).
- **k-NN Algorithm**: Prediksi berdasarkan tetangga terdekat di ruang fitur.

4. Insight & Ringkasan
- Udah diperlihatkan cara loading dataset, splitting data, training model, dan evaluasi model.
- Akurasi 97% dicapai pake k-NN di dataset Iris.
- Algoritma k-NN itu sederhana tapi efektif buat dataset kecil.
"""