# -*- coding: utf-8 -*-
"""Bab 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L91Y7GLtwqbWMigfIwXYcLvuGXziqBy5

# Bab 5: Model Evaluation and Improvement (Evaluasi dan Peningkatan Model)

# Bab 5: Model Evaluation and Improvement (Evaluasi dan Peningkatan Model)

## 1. Tujuan
Bab ini membahas bagaimana mengevaluasi performa model machine learning secara objektif dan cara meningkatkan performanya melalui teknik seperti cross-validation, grid search, dan pemilihan metrik evaluasi yang tepat.

2. Implementasi Kode
"""

# 2.1 Cross-Validation
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris

# Load dataset Iris
iris = load_iris()
X, y = iris['data'], iris['target']

# RandomForest dengan cross-validation
clf = RandomForestClassifier(random_state=0)
scores = cross_val_score(clf, X, y, cv=5)
print("Cross-validation scores:", scores)
print("Rata-rata skor:", scores.mean())

### 2.2 Grid Search
from sklearn.model_selection import GridSearchCV

# Parameter grid untuk RandomForest
param_grid = {'n_estimators': [10, 50, 100], 'max_depth': [None, 10, 20]}

# Grid search
grid_search = GridSearchCV(RandomForestClassifier(random_state=0), param_grid, cv=5)
grid_search.fit(X, y)
print("Best parameters:", grid_search.best_params_)
print("Best cross-validation score:", grid_search.best_score_)

"""## 3. Penjelasan Teoritis
- **Cross-Validation**: Membagi dataset menjadi beberapa lipatan (folds) untuk menghindari overfitting dan mendapatkan estimasi performa yang lebih akurat.
- **Grid Search**: Mencari kombinasi parameter terbaik untuk model menggunakan evaluasi berulang pada grid parameter.
- **Metrik Evaluasi**: Memilih metrik yang sesuai seperti akurasi, precision, recall, F1-score, atau AUC tergantung pada tujuan model.

## 4. Insight & Ringkasan
- Cross-validation membantu menghindari hasil evaluasi yang bias.
- Grid search mempermudah pencarian hyperparameter terbaik.
- Pemilihan metrik evaluasi yang tepat penting untuk memastikan model sesuai dengan kebutuhan aplikasi.
"""